import { screen } from '@testing-library/react';
import renderWithRouter from '../renderWithRouter';
import App from '../App';
import pokemons from '../data';

test('Teste para contemplar 100% dos casos de uso criados pelo Stryker', async () => {
  const { user } = renderWithRouter(<App />);
  const btnHhome = screen.getByRole('link', { name: /home/i });
  const btnAbout = screen.getByRole('link', { name: /about/i });
  const btnFavorite = screen.getByRole('link', { name: /favorite pokémon/i });
  const title = screen.getByRole('heading', { name: /encountered pokémon/i });
  const nextPokemon = screen.getByRole('button', { name: /próximo pokémon/i });
  const pikachu = screen.getByText(/pikachu/i);
  expect(title).toBeInTheDocument();
  expect(btnHhome).toBeInTheDocument();
  expect(btnAbout).toBeInTheDocument();
  expect(btnFavorite).toBeInTheDocument();
  expect(nextPokemon).toBeInTheDocument();
  pokemons.forEach(async (pokemon) => {
    const name = await screen.findByText(pokemon.name);
    expect(name).toBeInTheDocument();
    await user.click(nextPokemon);
  });
  expect(nextPokemon).toBeEnabled();
  await user.click(nextPokemon);
  const btnAll = screen.getByRole('button', { name: /all/i });
  const buttons = screen.getAllByTestId('pokemon-type-button');
  const allButtons = [btnAll, ...buttons];
  allButtons.forEach((button) => {
    expect(button).toBeInTheDocument();
  });
  const btnElectric = buttons[0];
  const btnFire = buttons[1];
  const btnBug = buttons[2];
  const btnPoison = buttons[3];
  const btnPsychic = buttons[4];
  const btnNormal = buttons[5];
  const btnDragon = buttons[6];
  await user.click(btnElectric);
  expect(pikachu).toBeInTheDocument();
  expect(nextPokemon).toBeDisabled();
  await user.click(btnFire);
  const charmander = screen.getByText(/charmander/i);
  expect(charmander).toBeInTheDocument();
  expect(nextPokemon).toBeEnabled();
  await user.click(nextPokemon);
  const rapidash = screen.getByText(/rapidash/i);
  expect(rapidash).toBeInTheDocument();
  await user.click(btnBug);
  const caterpie = screen.getByText(/caterpie/i);
  expect(caterpie).toBeInTheDocument();
  expect(nextPokemon).toBeDisabled();
  await user.click(btnPoison);
  const ekans = screen.getByText(/ekans/i);
  expect(ekans).toBeInTheDocument();
  expect(nextPokemon).toBeDisabled();
  await user.click(btnPsychic);
  const alakazam = screen.getByText(/alakazam/i);
  expect(alakazam).toBeInTheDocument();
  expect(nextPokemon).toBeEnabled();
  await user.click(nextPokemon);
  const mew = screen.getByText(/mew/i);
  expect(mew).toBeInTheDocument();
  await user.click(btnNormal);
  const snorlax = screen.getByText(/snorlax/i);
  expect(snorlax).toBeInTheDocument();
  expect(nextPokemon).toBeDisabled();
  await user.click(btnDragon);
  const dragonair = screen.getByText(/dragonair/i);
  expect(dragonair).toBeInTheDocument();
  expect(nextPokemon).toBeDisabled();
  await user.click(btnAll);
  expect(nextPokemon).toBeEnabled();
});
